name: Cypress Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8
        env:
          MYSQL_DATABASE: HMS
          MYSQL_ROOT_PASSWORD: root
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping --silent" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Build backend
        run: |
          cd HospitalManagementSystembackend
          ./mvnw clean package -DskipTests

      - name: Start backend
        run: |
          java -jar HospitalManagementSystembackend/target/*.jar &
          sleep 30

      - name: Install frontend dependencies
        run: |
          cd "Hospital Management System ui"
          npm install

      - name: Start frontend
        run: |
          cd "Hospital Management System ui"
          npx http-server -p 8081 &
          sleep 5

      - name: Run Cypress tests
        run: |
          cd "Hospital Management System ui"
          npx cypress run 